CREATE DATABASE HOSPTJAVA;

USE HOSPTJAVA;

-- FUNCIONÁRIOS
CREATE TABLE ESPECIALIDADE (
    ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
    NOME_ESPECIALIDADE ENUM('Pediatria', 'Clínica Geral', 'Gastroenterologia', 'Dermatologia'),
    PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE MEDICO (
    ID_MEDICO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(12) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    TIPO INT,
    PRIMARY KEY (ID_MEDICO),
    FOREIGN KEY (TIPO) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

CREATE TABLE ENFERMEIRO (
    ID_ENFERMEIRO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(12) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    TIPO INT,
    PRIMARY KEY (ID_ENFERMEIRO),
    FOREIGN KEY (TIPO) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

-- CLIENTES
CREATE TABLE CONVENIO (
    ID_CONVENIO INT NOT NULL AUTO_INCREMENT,
    NOME_CONVENIO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CONVENIO)
);

CREATE TABLE PACIENTE (
    ID_PACIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(12) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    ID_CONVENIO_CLIENTE INT,
    PRIMARY KEY (ID_PACIENTE),
    FOREIGN KEY (ID_CONVENIO_CLIENTE) REFERENCES CONVENIO(ID_CONVENIO)
);

-- INFRAESTRUTURA
CREATE TABLE QUARTO (
    ID_QUARTO INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID_QUARTO)
);

-- CONSULTA
CREATE TABLE MEDICAMENTO (
    ID_REMEDIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_REMEDIO)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
    DATA_HORA DATETIME NOT NULL,
    PACIENTE INT NOT NULL,
    MEDICO INT NOT NULL,
    CONVENIO INT NOT NULL,
    PRIMARY KEY (ID_CONSULTA),
    FOREIGN KEY (PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (CONVENIO) REFERENCES CONVENIO(ID_CONVENIO)
);

CREATE TABLE RECEITA (
    ID_RECEITA INT NOT NULL AUTO_INCREMENT,
    DATA_EMISSAO DATE NOT NULL,
    ID_MEDICAMENTO INT NOT NULL,
    OBSERVACAO LONGTEXT,
    ID_CONSULTA INT,
    PRIMARY KEY (ID_RECEITA),
    FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_REMEDIO),
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

-- INTERNAÇÃO
CREATE TABLE INTERNACAO (
    ID_INTERNACAO INT NOT NULL AUTO_INCREMENT,
    DATA_ENTRADA DATE NOT NULL,
    DATA_PREVISAO_ALTA DATE NOT NULL,
    DATA_SAIDA DATE,
    ID_INTERNACAO_PACIENTE INT,
    ID_INTERNACAO_MEDICO INT,
    ID_INTERNACAO_ENFERMEIRO INT,
    ID_INTERNACAO_CONVENIO INT,
    ID_NUMERO_QUARTO INT,
    PRIMARY KEY (ID_INTERNACAO),
    FOREIGN KEY (ID_INTERNACAO_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_INTERNACAO_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_INTERNACAO_ENFERMEIRO) REFERENCES ENFERMEIRO(ID_ENFERMEIRO),
    FOREIGN KEY (ID_INTERNACAO_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO),
    FOREIGN KEY (ID_NUMERO_QUARTO) REFERENCES QUARTO(ID_QUARTO)
);

-- TRIGGER: limita 2 pacientes por quarto
DELIMITER //

CREATE TRIGGER limitar_pacientes_por_quarto
BEFORE INSERT ON INTERNACAO
FOR EACH ROW
BEGIN
    DECLARE qtd INT;

    SELECT COUNT(*) INTO qtd
    FROM INTERNACAO
    WHERE ID_NUMERO_QUARTO = NEW.ID_NUMERO_QUARTO
      AND DATA_SAIDA IS NULL;

    IF qtd >= 2 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Este quarto já possui 2 pacientes ativos.';
    END IF;
END //

DELIMITER ;