SHOW TABLES;
SHOW TABLE STATUS;

-- FUNCIONÁRIOS
SELECT * FROM ESPECIALIDADE;
SELECT * FROM MEDICO;
SELECT * FROM MEDICO_ESPECIALIDADE;
SELECT * FROM ENFERMEIRO;

-- CLIENTES
SELECT * FROM CONVENIO;
SELECT * FROM PACIENTE;

-- INFRAESTRUTURA
SELECT * FROM QUARTO;

-- CONSULTA E RECEITA
SELECT * FROM MEDICAMENTO;
SELECT * FROM CONSULTA;
SELECT * FROM RECEITA;

-- INTERNAÇÃO
SELECT * FROM INTERNACAO;

-- VER DUAS 
SELECT 'MÉDICO' AS TIPO_FUNCIONARIO, ID_MEDICO AS ID, NOME, CPF, DATA_DE_NASCIMENTO, EMAIL, TIPO
FROM MEDICO
UNION ALL
SELECT 'ENFERMEIRO' AS TIPO_FUNCIONARIO, ID_ENFERMEIRO AS ID, NOME, CPF, DATA_DE_NASCIMENTO, EMAIL, TIPO
FROM ENFERMEIRO;




