
-- Quarto
ALTER TABLE QUARTO 
ADD COLUMN TIPO ENUM('Apartamento', 'Quarto Duplo', 'Enfermaria') NOT NULL AFTER ID_QUARTO,
ADD COLUMN VALOR_DIARIA DECIMAL(10,2) NOT NULL AFTER TIPO;

-- Especialidades
ALTER TABLE ESPECIALIDADE 
MODIFY NOME_ESPECIALIDADE ENUM('Pediatria', 'Clínica Geral', 'Gastroenterologia', 'Dermatologia', 'Ortopedia', 'Cardiologia', 'Neurologia','Odontologia');

-- Internações
ALTER TABLE INTERNACAO 
ADD COLUMN MOTIVO VARCHAR(100) NOT NULL AFTER DATA_ENTRADA;

-- Criando a tabela de relação do Medico com a Especialidade
ALTER TABLE MEDICO DROP FOREIGN KEY medico_ibfk_1;
ALTER TABLE MEDICO DROP COLUMN TIPO;
CREATE TABLE MEDICO_ESPECIALIDADE (
    ID_MEDICO INT NOT NULL,
    ID_ESPECIALIDADE INT NOT NULL,
    PRIMARY KEY (ID_MEDICO, ID_ESPECIALIDADE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES ESPECIALIDADE(ID_ESPECIALIDADE)
);

-- Criando a tabela de relação do Internação com Enfermeiros
CREATE TABLE INTERNACAO_ENFERMEIRO (
    ID_INTERNACAO INT NOT NULL,
    ID_ENFERMEIRO INT NOT NULL,
    FUNCAO ENUM ('ENFERMEIRO', 'RESPONSÁVEL', 'ASSISTENTE', 'PLANTONISTA'),
    PRIMARY KEY (ID_INTERNACAO, ID_ENFERMEIRO),
    FOREIGN KEY (ID_INTERNACAO) REFERENCES INTERNACAO(ID_INTERNACAO),
    FOREIGN KEY (ID_ENFERMEIRO) REFERENCES ENFERMEIRO(ID_ENFERMEIRO)
);

-- Criando a tabela de relação do Medico com Convenio
CREATE TABLE MEDICO_CONVENIO (
    ID_MEDICO INT NOT NULL,
    ID_CONVENIO INT NOT NULL,
    PRIMARY KEY (ID_MEDICO, ID_CONVENIO),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_CONVENIO) REFERENCES CONVENIO(ID_CONVENIO)
);

-- Corrigindo as chaves de alteração 
ALTER TABLE INTERNACAO
ADD CONSTRAINT fk_internacao_paciente
FOREIGN KEY (ID_INTERNACAO_PACIENTE)
REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE INTERNACAO
ADD CONSTRAINT fk_internacao_medico
FOREIGN KEY (ID_INTERNACAO_MEDICO)
REFERENCES MEDICO(ID_MEDICO);

ALTER TABLE INTERNACAO
ADD CONSTRAINT fk_internacao_convenio
FOREIGN KEY (ID_INTERNACAO_CONVENIO)
REFERENCES CONVENIO(ID_CONVENIO);

ALTER TABLE INTERNACAO
ADD CONSTRAINT fk_internacao_quarto
FOREIGN KEY (ID_NUMERO_QUARTO)
REFERENCES QUARTO(ID_QUARTO);





